on: [push]
 
jobs:
  sigma_download_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
 
      - name: Download SIGMA
        run: curl -k -L https://artifactory.internal.synopsys.com/artifactory/sigma-local/released/get | bash
 
      - name: SIGMA analysis
        run: ./sigma analyze .
